from setuptools import setup, find_packages

setup(
    name="hyperion3",
    version="2.0.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.21.0",
        "pandas>=1.3.0",
        "torch>=1.9.0",
        "scikit-learn>=0.24.0",
        "flaml>=2.3.5",
        "optuna>=2.10.0",
        "tensorboard>=2.6.0",
        "matplotlib>=3.4.0",
        "seaborn>=0.11.0",
        "ta>=0.7.0",
        "yfinance>=0.1.70",
        "ccxt>=1.60.0",
        "python-dotenv>=0.19.0",
        "tqdm>=4.62.0",
        "joblib>=1.0.0",
        "requests>=2.26.0",
        "websockets>=10.0",
        "aiohttp>=3.8.0",
        "asyncio>=3.4.3",
        "pytest>=6.2.5",
        "pytest-asyncio>=0.16.0",
        "pytest-cov>=2.12.0",
        "black>=21.9b0",
        "isort>=5.9.0",
        "flake8>=3.9.0",
        "mypy>=0.910",
        "pre-commit>=2.15.0",
    ],
    python_requires=">=3.8",
    author="Hyperion Team",
    author_email="hyperion@example.com",
    description="Hyperion V2 - Advanced Trading System",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/hyperion/hyperion3",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Office/Business :: Financial :: Investment",
    ],
)
